name: actions的使用
on: workflow_dispatch

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: find pwd
        run: |
          pwd
          ls -lh
      - uses: actions/checkout@v6
      - name: npm install
        run: npm install
      - name: npm start
        run: npm start
      - name: find pwd
        run: |
          pwd
          ls -lh
